version: '3.8'

services:

  frontend:
    build: frontend_react
    volumes:
      - frontend:/app/build

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./backend_django/static/:/usr/share/nginx/html/static/
      - ./backend_django/media/:/usr/share/nginx/html/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
    restart: always
    depends_on:
      - frontend

volumes:
  frontend:
